// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PollWebApi.Context;

namespace PollWebApi.Migrations
{
    [DbContext(typeof(PollContext))]
    [Migration("20200804021329_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PollWebApi.Models.OptionClass", b =>
                {
                    b.Property<long>("option_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("option_description")
                        .IsRequired();

                    b.Property<long>("poll_id");

                    b.HasKey("option_id");

                    b.HasIndex("poll_id");

                    b.ToTable("option");
                });

            modelBuilder.Entity("PollWebApi.Models.PollClass", b =>
                {
                    b.Property<long>("poll_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("poll_description")
                        .IsRequired();

                    b.HasKey("poll_id");

                    b.ToTable("poll");
                });

            modelBuilder.Entity("PollWebApi.Models.PollViewClass", b =>
                {
                    b.Property<long>("pollview_id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("poll_id");

                    b.HasKey("pollview_id");

                    b.HasIndex("poll_id");

                    b.ToTable("pollview");
                });

            modelBuilder.Entity("PollWebApi.Models.VoteClass", b =>
                {
                    b.Property<long>("vote_id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("option_id");

                    b.HasKey("vote_id");

                    b.HasIndex("option_id");

                    b.ToTable("vote");
                });

            modelBuilder.Entity("PollWebApi.Models.OptionClass", b =>
                {
                    b.HasOne("PollWebApi.Models.PollClass", "Poll")
                        .WithMany("options")
                        .HasForeignKey("poll_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PollWebApi.Models.PollViewClass", b =>
                {
                    b.HasOne("PollWebApi.Models.PollClass", "Poll")
                        .WithMany()
                        .HasForeignKey("poll_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PollWebApi.Models.VoteClass", b =>
                {
                    b.HasOne("PollWebApi.Models.OptionClass", "Option")
                        .WithMany()
                        .HasForeignKey("option_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
